### ISSUE TITLE
Kogito Service with Kogito Operator example not working

### ISSUE THREAD

**Issue by aramashkan** [kiegroup/kogito-cloud-operator#724]
Started learning Kogito by examples using minikube with installed registry and kogito operator. Based on example in [dev-guide](https://github.com/kiegroup/kogito-cloud-operator/blob/1.0.x/docs/GUIDE_TO_KOGITO_DEVS.md) tried to create kogito service but received following error:

`The KogitoRuntime "process-business-rules-quarkus" is invalid: spec.image: Invalid value: "object": spec.image in body must be of type string: "object"`

I changed image value to full address  for my image in minikube registry :

`apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: dmn-springboot-example
spec:
  replicas: 1
  image: 192.168.64.6:5000/dmn-springboot-example:latest`

After successfully created pod can't start with error :

`Failed to apply default image tag "quay.io/192.168.64.6:5000/dmn-springboot-example:latest": couldn't parse image reference "quay.io/192.168.64.6:5000/dmn-springboot-example:latest": invalid reference format`

Why quay.io is prefix ? How can i use my local registry ?

**Comment by Kaitou786** [comment]
Hello @aramashkan, thanks for opening the issue. 

First: We will update the docs to replicate the change of the image format to receive a string instead of object.

Second: The regex we use assumes the image to have 3 parts `(registry_url/some_namespace/your_image)`. Since you are giving a image with only two things it is appending the default registry in front of it.
For now if you are using your local registry I suggest you can try with putting `somenamespace` in your image.
So instead of `192.168.64.6:5000/dmn-springboot-example:latest` it'll be `192.168.64.6:5000/<any_namespace>/dmn-springboot-example:latest`.
 
PS: if you are using the registry:2 image to deploy your internal registry server you would be able to push the image by putting anything in the namespace field.
So you can do 
```
docker tag 192.168.64.6:5000/dmn-springboot-example:latest 192.168.64.6:5000/mynamespace/dmn-springboot-example:latest
docker push 192.168.64.6:5000/mynamespace/dmn-springboot-example:latest
```
And then use this in image field of kogitoRuntime.

**Comment by aramashkan** [comment]
Yep it's worked ! Thanks!
